In [1]:
%pip install -q libpysal esda splot mapclassify contextily

In [2]:
DATA_BASE = "https://raw.githubusercontent.com/pjbitterman/KSU_x9076/main/data"

import pandas as pd

ohio_precip = pd.read_csv(f"{DATA_BASE}/part1/ohio_precip_2025.csv")
ohio_precip.head()

    station_id               name      lat      lon  precip_mm_2025
0  US1OHAB0021  ASHTABULA 1.8 NNE  41.9037 -80.7829           910.4
1  US1OHAD0005       SEAMAN 3.4 E  38.9399 -83.5090          1270.7
2  US1OHAD0006      PEEBLES 4.2 N  39.0075 -83.4146          1174.8
3  US1OHAL0005        LIMA 2.7 NE  40.7739 -84.0800           904.3
4  US1OHAL0008    DELPHOS 2.3 ESE  40.8335 -84.2982           711.4

In [3]:
ohio_precip["precip_mm_2025"].describe()

count     410.000000
mean     1008.862439
std       174.937689
min       350.900000
25%       895.575000
50%      1014.050000
75%      1125.500000
max      1495.700000
Name: precip_mm_2025, dtype: float64

In [4]:
wettest_stations = ohio_precip.sort_values("precip_mm_2025", ascending=False)
wettest_stations.head()

,station_id,name,lat,lon,precip_mm_2025
406,USW00093812,CINCINNATI MUNI AP LUNKEN FLD,39.1061,-84.4161,1495.7
228,US1OHRC0007,SHELBY 0.6 NNE,40.8900,-82.6558,1488.7
16,US1OHAT0021,ATHENS 4.6 ESE,39.3099,-82.0128,1431.6
108,US1OHGG0007,MIDDLEFIELD 0.6 NE,41.4644,-81.0652,1411.7
48,US1OHCN0024,MIDLAND 2.9 S,39.2651,-83.9202,1402.5

In [5]:
final_table = wettest_stations.head()
final_table[["name", "precip_mm_2025"]]

                              name  precip_mm_2025
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7
228                 SHELBY 0.6 NNE          1488.7
16                  ATHENS 4.6 ESE          1431.6
108             MIDDLEFIELD 0.6 NE          1411.7
48                   MIDLAND 2.9 S          1402.5

In [6]:
final_table = wettest_stations.head().copy()
final_table["mean"] = ohio_precip["precip_mm_2025"].mean()
final_table[["name", "precip_mm_2025", "mean"]]

                              name  precip_mm_2025         mean
406  CINCINNATI MUNI AP LUNKEN FLD          1495.7  1008.862439
228                 SHELBY 0.6 NNE          1488.7  1008.862439
16                  ATHENS 4.6 ESE          1431.6  1008.862439
108             MIDDLEFIELD 0.6 NE          1411.7  1008.862439
48                   MIDLAND 2.9 S          1402.5  1008.862439

In [7]:
wettest_station = final_table.iloc[0]
difference = wettest_station["precip_mm_2025"] - wettest_station["mean"]
print(round(difference, 2))

486.84

The wettest station "CINCINNATI MUNI AP LUNKEN FLD" is 486.84 mm above the mean precipitation.
It doesn't surprise me, the station is next to the Ohio River valley so it gets a lot of moisture from it and this exposure tends to make the air of a place more humid, encreasing the probability of rain.